# Generated by Django 4.1 on 2022-09-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampled_at', models.IntegerField()),
                ('a_x', models.FloatField()),
                ('a_y', models.FloatField()),
                ('a_z', models.FloatField()),
                ('g_x', models.FloatField()),
                ('g_y', models.FloatField()),
                ('g_z', models.FloatField()),
                ('m_x', models.FloatField()),
                ('m_y', models.FloatField()),
                ('m_z', models.FloatField()),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'imu',
            },
        ),
    ]
