# Generated by Django 4.1 on 2022-10-19 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_heartrate_routine_remove_imu_routine_and_more'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='services.routine'),
        ),
        migrations.AlterField(
            model_name='heartrate',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate', to='services.routine'),
        ),
        migrations.AlterField(
            model_name='imu',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imu', to='services.routine'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='services.routine'),
        ),
        migrations.CreateModel(
            name='Magnetometer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampled_at', models.IntegerField()),
                ('m_x', models.FloatField()),
                ('m_y', models.FloatField()),
                ('m_z', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magnetometer', to='services.routine')),
            ],
            options={
                'db_table': 'magnetometer',
            },
        ),
    ]
