# Generated by Django 4.1 on 2022-10-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_audio_routine_alter_heartrate_routine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imu',
            name='m_x',
        ),
        migrations.RemoveField(
            model_name='imu',
            name='m_y',
        ),
        migrations.RemoveField(
            model_name='imu',
            name='m_z',
        ),
    ]
