# Generated by Django 4.1 on 2022-09-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dog_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampled_at', models.IntegerField()),
                ('value', models.FloatField(default=0.0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.routine')),
            ],
            options={
                'db_table': 'temperature',
            },
        ),
        migrations.CreateModel(
            name='Imu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampled_at', models.IntegerField()),
                ('a_x', models.FloatField()),
                ('a_y', models.FloatField()),
                ('a_z', models.FloatField()),
                ('g_x', models.FloatField()),
                ('g_y', models.FloatField()),
                ('g_z', models.FloatField()),
                ('m_x', models.FloatField()),
                ('m_y', models.FloatField()),
                ('m_z', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.routine')),
            ],
            options={
                'db_table': 'imu',
            },
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sampled_at', models.IntegerField()),
                ('value', models.FloatField(default=0.0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.routine')),
            ],
            options={
                'db_table': 'heart_rate',
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=300)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.routine')),
            ],
            options={
                'db_table': 'audio',
            },
        ),
    ]
