# Generated by Django 4.1 on 2022-09-03 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='routine',
            table='routine',
        ),
    ]
