# Generated by Django 4.1 on 2022-09-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartrate',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='imu',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='routine',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='HeartRate',
        ),
        migrations.DeleteModel(
            name='Imu',
        ),
        migrations.DeleteModel(
            name='Temperature',
        ),
    ]
