# Generated by Django 4.1 on 2022-09-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
        ('services', '0004_remove_heartrate_routine_remove_imu_routine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='imus',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='sensors.imu'),
        ),
    ]
